# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: citylex.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rcitylex.proto\x12\x07\x63itylex"\x84\x04\n\x05\x45ntry\x12\x12\n\ncelex_freq\x18\x01 \x01(\x03\x12\x17\n\x0fsubtlex_uk_freq\x18\x02 \x01(\x03\x12\x15\n\rsubtlex_uk_cd\x18\x03 \x01(\x03\x12\x17\n\x0fsubtlex_us_freq\x18\x04 \x01(\x03\x12\x15\n\rsubtlex_us_cd\x18\x05 \x01(\x03\x12/\n\x0b\x63\x65lex_morph\x18\x06 \x03(\x0b\x32\x1a.citylex.Entry.MorphTriple\x12\x14\n\x0c\x65lp_morph_sp\x18\x07 \x01(\t\x12\x12\n\nelp_nmorph\x18\x08 \x01(\x05\x12\x34\n\x10udlexicons_morph\x18\t \x03(\x0b\x32\x1a.citylex.Entry.MorphTriple\x12\x32\n\x0eunimorph_morph\x18\n \x03(\x0b\x32\x1a.citylex.Entry.MorphTriple\x12\x12\n\ncelex_pron\x18\x0b \x03(\t\x12\x14\n\x0c\x63mudict_pron\x18\x0c \x03(\t\x12\x18\n\x10wikipron_uk_pron\x18\r \x03(\t\x12\x18\n\x10wikipron_us_pron\x18\x0e \x03(\t\x1a.\n\x0bMorphTriple\x12\r\n\x05lemma\x18\x01 \x02(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x03 \x01(\t\x1a\x34\n\x0cSegmentation\x12\x14\n\x0csegmentation\x18\x01 \x02(\t\x12\x0e\n\x06nmorph\x18\x02 \x02(\x05"s\n\x07Lexicon\x12*\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x1b.citylex.Lexicon.EntryEntry\x1a<\n\nEntryEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.citylex.Entry:\x02\x38\x01'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "citylex_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _LEXICON_ENTRYENTRY._options = None
    _LEXICON_ENTRYENTRY._serialized_options = b"8\001"
    _ENTRY._serialized_start = 27
    _ENTRY._serialized_end = 543
    _ENTRY_MORPHTRIPLE._serialized_start = 443
    _ENTRY_MORPHTRIPLE._serialized_end = 489
    _ENTRY_SEGMENTATION._serialized_start = 491
    _ENTRY_SEGMENTATION._serialized_end = 543
    _LEXICON._serialized_start = 545
    _LEXICON._serialized_end = 660
    _LEXICON_ENTRYENTRY._serialized_start = 600
    _LEXICON_ENTRYENTRY._serialized_end = 660
# @@protoc_insertion_point(module_scope)
