version: 2

workflows:
  version: 2
  test:
    jobs:
      - python3.8
      - python3.9
      - python3.10
      - python3.11
jobs:
  python3.8: &template
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install the full development requirements
          working_directory: ~/project/
          command: pip install --progress-bar off -r requirements.txt
      - run:
          name: Run flake8 check
          working_directory: ~/project
          command: flake8 citylex.py
      - run:
          name: Run black check
          working_directory: ~/project
          command: black --line-length 79 --check citylex.py
      - run:
          name: Build source distribution
          working_directory: ~/project/
          command: |
              python -m build
              pip install dist/`ls dist/ | grep .whl`
  python3.9:
    <<: *template
    docker:
      - image: python:3.9
  python3.10:
    <<: *template
    docker:
      - image: python:3.10
  python3.11:
    <<: *template
    docker:
      - image: python:3.11
