version: 2

workflows:
  version: 2
  test:
    jobs:
      - python-3.7
      - python-3.8
      - python-3.9
      - python-3.10

jobs:
  python-3.7: &template
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Build source distribution and install package from it
          working_directory: ~/project/
          # Ensure we can build a source distribution that can correctly install.
          # "python setup.py sdist" creates dist/citylex-x.y.z.tar.gz
          command: |
              pip install --progress-bar off --upgrade pip setuptools
              python setup.py sdist
              pip install dist/`ls dist/ | grep .tar.gz`
      - run:
          name: Install the full development requirements
          working_directory: ~/project/
          command: pip install --progress-bar off -r requirements.txt
      - run:
          name: Show installed Python packages
          command: pip list
      - run:
          name: Lint
          working_directory: ~/
          # Avoid being able to import citylex by relative import.
          # Test code by importing the *installed* citylex in site-packages.
          command: flake8 project/setup.py project/citylex
  python-3.8:
    <<: *template
    docker:
      - image: python:3.8
  python-3.9:
    <<: *template
    docker:
      - image: python:3.9
  python-3.10:
    <<: *template
    docker:
      - image: python:3.10
