version: 2

workflows:
  version: 2
  test:
    jobs:
      - python3.7
      - python3.8
      - python3.9
      - python3.10

jobs:
  python3.7: &template
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install the full development requirements
          working_directory: ~/project/
          command: pip install --progress-bar off -r requirements.txt
      - run:
          name: Run flake8 check
          working_directory: ~/project
          command: flake8 citylex.py setup.py
      - run:
          name: Run black check
          working_directory: ~/project
          command: black --line-length 79 --check citylex.py setup.py
      - run:
          name: Build source distribution
          working_directory: ~/project/
          # Ensure we can build a source distribution that can correctly install.
          # "python setup.py sdist" creates dist/citylex-x.y.z.tar.gz
          command: |
              pip install --progress-bar off --upgrade pip setuptools
              python setup.py sdist
              pip install dist/`ls dist/ | grep .tar.gz`
  python3.8:
    <<: *template
    docker:
      - image: python:3.8
  python3.9:
    <<: *template
    docker:
      - image: python:3.9
  python3.10:
    <<: *template
    docker:
      - image: python:3.10
